---
# import php runtime meta data
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    drupal_vhost_dir: "{{php_runtime_meta[ansible_os_family][drupal_webs].vhost_dir}}"
    drupal_vhost_src: "{{php_runtime_meta[ansible_os_family][drupal_webs].vhost_src}}"
    drupal_service: "{{php_runtime_meta[ansible_os_family][drupal_webs].service}}"
    drupal_owner: "{{php_runtime_meta[ansible_os_family][drupal_webs].owner}}"
    drupal_db_password: "{{mysql_root_password}}"

- debug:
    msg: runtime {{ drupal_vhost_dir }}, {{drupal_vhost_src}}, {{drupal_service}}, {{drupal_owner}}, {{drupal_webs}}, {{ansible_distribution}}

# Drupal
- name: Remove extra dir for sec_installation
  shell: rm -rf /data/wwwroot/{{drupal_name}}
  
- name: Create drupal User
  user:
    name: drupal
    shell: /bin/bash

- name: Create drupal cli directory
  file:
    path: '/data/wwwroot/{{item}}'
    state: directory
    recurse: yes
  with_items:
    - drupal_console
    - drush

- name: Add drupal Permission
  shell: |
    setfacl -R -m  u:drupal:rwx /data/wwwroot/
    setfacl -m u:drupal:rx /bin/composer

- block:  
  - name: Use composer install drupal 
    shell: composer create-project drupal/recommended-project /data/wwwroot/{{drupal_name}}

  - name: Use composer install drush cli
    shell: composer require drush/drush
    args:
      chdir: /data/wwwroot/drush
  
  - name: Use composer install drupal_console cli
    shell: composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
    args:
      chdir: /data/wwwroot/drupal_console
  become_method: su
  become_user: drupal

- block:
  - name: Get  drush cli 
    shell: ls /data/wwwroot/drush/vendor/bin/
    register: drush_cli

  - name: Get drupal_console cli
    shell: ls /data/wwwroot/drupal_console/vendor/bin/
    register: drupal_console_cli

  - name: Set link for cli
    file:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
      state: link
      force: yes
    with_items:
      - {src: '/data/wwwroot/drush/vendor/bin/{{drush_cli.stdout_lines |list}}' ,dest: '/usr/bin/{{drush_cli.stdout_lines |list}}'}
      - {src: '/data/wwwroot/drupal_console/vendor/bin/{{drupal_console_cli.stdout_lines |list}}' ,dest: '/usr/bin/{{drupal_console_cli.stdout_lines |list}}'}

  # 系统通用
- name: Permission directory
  shell: |
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{drupal_owner}}:{{drupal_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{drupal_vhost_src}} dest={{drupal_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{drupal_service}} state=restarted enabled=yes

  - name: restart php-fpm
    service: name=php-fpm state=restarted
